[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc_version = "0.8.28"
ignored_error_codes = [5740]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# Formatter configuration
[fmt]
line_length = 100

evm_version = "prague"


